apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: random-dev
  namespace: argocd

spec:
  project: random

  source:
    repoURL: https://github.com/SantiagoLemoMayoral/random.git
    targetRevision: main
    path: helm/random

    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: random-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true