apiVersion: v1
kind: Service

metadata:
  name: helpdesk

spec:

  type: {{ .Values.service.type }}

  selector:
    app: helpdesk

  ports:

    - name: http

      port: {{ .Values.service.port }}

      targetPort: http