name: CI-CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: helpdesk
  VALUES_FILE: helm/helpdesk/values.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate GitHub -> AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Login to ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Docker image
      - name: Build image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            .

      # 5. Push Docker image to ECR
      - name: Push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 6. Install yq
      - name: Install yq
        run: |
          sudo wget \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -O /usr/local/bin/yq

          sudo chmod +x /usr/local/bin/yq

      # 7. Change Helm image tag
      - name: Update Helm image tag
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          yq -i '.image.tag = strenv(IMAGE_TAG)' $VALUES_FILE

      # 8. Commit new desired state
      - name: Commit Helm change
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add $VALUES_FILE

          git commit -m "deploy: ${{ github.sha }}" || exit 0

          git push